# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/msm8998-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter beckham chef evert lake payton nash messi,$(TARGET_DEVICE)),)

endif
